GO
CREATE DATABASE Project_Sem3
GO
USE Project_Sem3
GO
CREATE TABLE GroupProduct
(
	ID INT PRIMARY KEY IDENTITY,
	GroupProduct_Id NVARCHAR(50) NULL,
	GroupProduct_Name NVARCHAR(50) NULL
)
--DROP TABLE GroupProduct
GO
CREATE TABLE Units
(
	ID INT PRIMARY KEY IDENTITY,
	Units_Id NVARCHAR(50) NULL,
	Units_Name NVARCHAR(50) NULL,
)
--DROP TABLE Units
GO
CREATE TABLE Product
(
	ID INT PRIMARY KEY IDENTITY,
	Product_Id NVARCHAR(50) NULL,
	Product_Name NVARCHAR(50) NULL,
	Price FLOAT,
	Date_Import DATETIME,
	fk_GroupProduct_ID INT  ,
	fk_Units_ID INT,
	fk_Experiment_ID INT
)

--DROP TABLE Product
GO
CREATE TABLE Experiments
(
	ID INT PRIMARY KEY IDENTITY,
	Name_experi NVARCHAR(100),
	Details NVARCHAR(MAX),
	Price FLOAT,
)
--DROP TABLE Orders
GO
CREATE TABLE Orders
(
	ID INT PRIMARY KEY IDENTITY,
	Order_ID NVARCHAR(50) NULL,
	Date_Export DATETIME,
	fk_Emp_ID INT,
	fk_Cus_ID INT,
	[Status] INT,
)

--DROP TABLE Order_Detail
GO
CREATE TABLE Order_Detail
(
	ID INT PRIMARY KEY IDENTITY,
	fk_Experiment_ID INT,
	fk_Order_ID INT,
	Quantity INT,
	Total DECIMAL(18,0)
)
--DROP TABLE Employee
GO
CREATE TABLE Employee
(
	Emp_ID INT PRIMARY KEY IDENTITY,
	FullName NVARCHAR(50) NOT NULL,
	UserName VARCHAR(50) NOT NULL,
	[PASSWORD] VARCHAR(50) NOT NULL,
	Date_Born DATETIME,
	Start_Date_Work DATETIME,
	[Address] NVARCHAR(MAX)NOT NULL,
	Email VARCHAR(50) NOT NULL,
	PhoneNumber INT NOT NULL,
	Gender NVARCHAR(50) NOT NULL,
	Educational_level NVARCHAR(50),
	[Role] INT NOT NULL,
	[Status] INT,
	fk_CalamViec_ID INT,
	fk_Clinic_ID INT
)
--DROP TABLE Custommer
GO
CREATE TABLE Custommer
(
	Cus_ID INT PRIMARY KEY IDENTITY,
	FullName NVARCHAR(50) NOT NULL,
	UserName VARCHAR(50) NOT NULL,
	[Password] VARCHAR(50) NOT NULL,
	PhoneNumber INT,
	[Address] NVARCHAR(MAX) NOT NULL,
	Date_Register DATETIME,
	Email VARCHAR(50) NOT NULL
)
GO
CREATE TABLE CaLamViec
(
	ID INT PRIMARY KEY IDENTITY,
	Name_CaLamViec NVARCHAR(50) NULL,
	[Start] DATETIME,
	[End] DATETIME,
)
GO
CREATE TABLE Contact_Clinic
(
	ID INT PRIMARY KEY IDENTITY,
	[Name] NVARCHAR(50),
	[Address] NVARCHAR(MAX),
	Detail NVARCHAR(MAX),
	PhoneNumber INT,
	Email NVARCHAR(50)
)
CREATE TABLE News 
(
	ID INT IDENTITY PRIMARY KEY,
	Title NVARCHAR(100),
	Details NVARCHAR(MAX),
	Date_Post DATETIME
)
GO
ALTER TABLE Product ADD FOREIGN KEY (fk_Experiment_ID)  REFERENCES Experiments(ID) ON UPDATE CASCADE ON DELETE CASCADE 
GO
ALTER TABLE Product ADD FOREIGN KEY (fk_GroupProduct_ID)  REFERENCES GroupProduct(ID) ON UPDATE CASCADE ON DELETE CASCADE 
GO
ALTER TABLE Product ADD FOREIGN KEY (fk_Units_ID)  REFERENCES Units(ID) ON UPDATE CASCADE ON DELETE CASCADE 
GO
ALTER TABLE Order_Detail ADD FOREIGN KEY (fk_Experiment_ID)  REFERENCES Experiments(ID) ON UPDATE CASCADE ON DELETE CASCADE 
GO
ALTER TABLE Order_Detail ADD FOREIGN KEY (fk_Order_ID)  REFERENCES Orders(ID) ON UPDATE CASCADE ON DELETE CASCADE 
GO
ALTER TABLE Orders ADD FOREIGN KEY (fk_Emp_ID)  REFERENCES Employee(Emp_ID) ON UPDATE CASCADE ON DELETE CASCADE 
GO
ALTER TABLE Orders ADD FOREIGN KEY (fk_Cus_ID)  REFERENCES Custommer(Cus_ID) ON UPDATE CASCADE ON DELETE CASCADE 
GO
ALTER TABLE Employee ADD FOREIGN KEY (fk_CalamViec_ID)  REFERENCES CaLamViec(ID) ON UPDATE CASCADE ON DELETE CASCADE 
GO
ALTER TABLE Employee ADD FOREIGN KEY (fk_Clinic_ID)  REFERENCES Contact_Clinic(ID) ON UPDATE CASCADE ON DELETE CASCADE 
GO